# Generated by Django 4.0.6 on 2022-07-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.CharField(default='No Picture', max_length=255),
            preserve_default=False,
        ),
    ]
